language: ruby

dist: xenial

services:
  - postgresql
  - mysql

rvm:
  - 2.0.0

gemfile:
  - gemfiles/active_record_42.gemfile

env:
  - DB=sqlite3

before_install:
  # install older versions of rubygems and bundler only on Ruby < 2.7
  - if [ `echo "${TRAVIS_RUBY_VERSION:0:3} < 2.7" | bc` == 1 ]; then gem i rubygems-update -v '<3' && update_rubygems; fi;
  - if [ `echo "${TRAVIS_RUBY_VERSION:0:3} < 2.7" | bc` == 1 ]; then gem i bundler -v '<2'; fi;
script: 'bundle exec rake test'

cache: bundler

matrix:
  fast_finish: true
