name: Ruby

on:
  - push
  - pull_request

jobs:
  build:
    services:
      mysql:
        image: mysql
        ports:
          - 3306:3306
        env:
          MYSQL_HOST: localhost
          MYSQL_USERNAME: root
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: kaminari_test
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      postgresql:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_HOST: localhost
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: kaminari_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      fail-fast: false
      matrix:
        ruby_version:
          - ruby-head
          - '3.0'
          - '2.7'
          - '2.6'
          - '2.5'
          - '2.4'
          - '2.3'
        gemfile:
          - gemfiles/active_record_61.gemfile
          - gemfiles/active_record_60.gemfile
          - gemfiles/active_record_52.gemfile
          - gemfiles/active_record_51.gemfile
          - gemfiles/active_record_50.gemfile
          - gemfiles/active_record_42.gemfile
          - gemfiles/active_record_41.gemfile
          - gemfiles/active_record_edge.gemfile
        db:
          - sqlite3
          - postgresql
          - mysql
        exclude:
          - ruby_version: '3.0'
            gemfile: gemfiles/active_record_52.gemfile
          - ruby_version: '3.0'
            gemfile: gemfiles/active_record_51.gemfile
          - ruby_version: '3.0'
            gemfile: gemfiles/active_record_50.gemfile
          - ruby_version: '3.0'
            gemfile: gemfiles/active_record_42.gemfile
          - ruby_version: '3.0'
            gemfile: gemfiles/active_record_41.gemfile
          - ruby_version: '2.7'
            gemfile: gemfiles/active_record_52.gemfile
          - ruby_version: '2.7'
            gemfile: gemfiles/active_record_51.gemfile
          - ruby_version: '2.7'
            gemfile: gemfiles/active_record_50.gemfile
          - ruby_version: '2.7'
            gemfile: gemfiles/active_record_42.gemfile
          - ruby_version: '2.7'
            gemfile: gemfiles/active_record_41.gemfile
          - ruby_version: '2.6'
            gemfile: gemfiles/active_record_edge.gemfile
          - ruby_version: '2.6'
            gemfile: gemfiles/active_record_42.gemfile
          - ruby_version: '2.6'
            gemfile: gemfiles/active_record_41.gemfile
          - ruby_version: '2.5'
            gemfile: gemfiles/active_record_edge.gemfile
          - ruby_version: '2.5'
            gemfile: gemfiles/active_record_42.gemfile
          - ruby_version: '2.5'
            gemfile: gemfiles/active_record_41.gemfile
          - ruby_version: '2.4'
            gemfile: gemfiles/active_record_edge.gemfile
          - ruby_version: '2.4'
            gemfile: gemfiles/active_record_61.gemfile
          - ruby_version: '2.4'
            gemfile: gemfiles/active_record_60.gemfile
          - ruby_version: '2.4'
            gemfile: gemfiles/active_record_42.gemfile
          - ruby_version: '2.4'
            gemfile: gemfiles/active_record_41.gemfile
          - ruby_version: '2.3'
            gemfile: gemfiles/active_record_edge.gemfile
          - ruby_version: '2.3'
            gemfile: gemfiles/active_record_61.gemfile
          - ruby_version: '2.3'
            gemfile: gemfiles/active_record_60.gemfile
          - ruby_version: ruby-head
            gemfile: gemfiles/active_record_42.gemfile
          - ruby_version: ruby-head
            gemfile: gemfiles/active_record_41.gemfile
        include:
          - ruby_version: ruby-head
            gemfile: gemfiles/active_record_edge.gemfile
            db: sqlite3
          - ruby_version: '2.2'
            gemfile: gemfiles/active_record_51.gemfile
            db: sqlite3
          - ruby_version: '2.1'
            gemfile: gemfiles/active_record_42.gemfile
            db: sqlite3
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      DB: ${{ matrix.db }}
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      MYSQL_HOST: localhost
      MYSQL_PORT: 3306
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true
      - name: Verify MySQL connection from host
        run: |
          sudo apt-get install -y mysql-client libmysqlclient-dev
          mysql --host 127.0.0.1 --port 3306 -uroot -proot -e "SHOW GRANTS FOR 'root'@'localhost'"
          mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql --host 127.0.0.1 --port 3306 -uroot -proot mysql
        continue-on-error: true
      - name: Very PostgreSQL connection from host
        run: |
          sudo apt install postgresql
          psql 'postgres://postgres:postgres@localhost:5432'
        continue-on-error: true
      - run: bundle exec rake test
